### ISSUE TITLE
Best practices when using add()

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/docs#11]
Explain details of the add method and best practices to avoid unexpected behaviour

From @yoavnash:
Specifically, it is better to initialize the cuds object all with the same session. Problematic scenario:
1. a is in the db (also in the db session)
1. b and c are in the core session
1. add b to a
1. add b to c
1. add c to wrapper
1. commit

Somehow the connection between a and b is not stored in the DB, probably because of mixing the session copies of the objects

**Comment by pablo-de-andres** [comment]
@urbanmatthias this sounds like it could be a bug, though?

**Comment by urbanmatthias** [comment]
I just took a closer look at this issue and it seems to be a bug.... I will investigate a bit more.

**Comment by urbanmatthias** [comment]
https://github.com/simphony/osp-core-migration/issues/432

I already spotted the bug and fixed it. Will merge asap.
