### ISSUE TITLE
Remove unused `sphinx-jsonschema` extension

### ISSUE THREAD

**Issue by harrytodorov** [simphony/docs#120]
Currently, we are installing the `sphinx-jsonschema` extension (see `docs/source/conf.py`), although we are not making use of it.
The extension, which allows the rendering of [JSON Schema](https://json-schema.org/) in the documentation, is also under the **GPL v3 License**, which is incompatible with our current license for the docs (BSD-3-Clause License).

**Comment by pablo-de-andres** [comment]
I will take care of this one since I am also gonna add a fix for the requirements versions in #131.
