### ISSUE TITLE
Fix small design issues

### ISSUE THREAD

**Issue by yoavnash** [simphony/docs#134]
- [x] Consistency with capitalization of headers
- [ ] ~~Binder explanation~~

Edit by @kysrpex:
- [x] Fix the style of _attributes_ in the CUDS API tutorial.
- [x] Center the contribute image about the branch management.
- [x] Mention license in the landing page (with link to License page)

**Comment by pablo-de-andres** [comment]
Will you also look here into the warnings from the Sphinx parser?

**Comment by kysrpex** [comment]
I'll add fixing the style of _attributes_ in the CUDS API tutorial.

**Comment by pablo-de-andres** [comment]
> Will you also look here into the warnings from the Sphinx parser?
Here we should at least look for broken links and references
