### ISSUE TITLE
Wrong value for format keyword in custom owl ontologies

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/docs#149]
In the specification on how to install custom ontologies, the format keyword is said to accept `rdf+xml` as a value (see [here](https://simphony.readthedocs.io/en/latest/owl.html#keywords)).
However, this is not an accepted value from rdflib (listed [here](https://rdflib.readthedocs.io/en/stable/plugin_parsers.html)). At most, it could be `application/rdf+xml`

**Comment by kysrpex** [comment]
For some reason we also listed `xml` and `application/rdf+xml` as different things, but they [point to the same parser](https://github.com/RDFLib/rdflib/blob/master/rdflib/plugin.py#L186).
