### ISSUE TITLE
Replace Recommonmark by MyST

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/docs#184]
[Recommonmark](https://github.com/readthedocs/recommonmark) is deprecated and no longer recommended by [Sphinx](https://www.sphinx-doc.org/en/master/usage/markdown.html). It should be replaced by [MyST](https://myst-parser.readthedocs.io/en/latest/).
- [x] `requirements.txt`
- [x] `docs/docs/source/conf.py` (extensions). See DSMS docs
- [x] Admonitions
- [x] `eval_rst` directive
- [x] Update: Check for directives inside admonitions

[Getting started guide](https://myst-parser.readthedocs.io/en/latest/sphinx/intro.html) from MyST

**Comment by kysrpex** [comment]
I spotted a bug in https://simphony.readthedocs.io/en/dev/contribute.html, probably due to this change.

![image](https://user-images.githubusercontent.com/43052541/134307167-d3d9f131-819a-416e-b20b-32bbbe1c02f1.png)
