### ISSUE TITLE
Add a contribute section

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/docs#35]

**Comment by pablo-de-andres** [comment]
Regarding the content:
 - SimPhoNy repo structure (OSP-core, docs, wrappers)
 - Working workflow (release, issue, branch, PR...) 
 - Asking for review

@yoavnash  @urbanmatthias

**Comment by urbanmatthias** [comment]
> SimPhoNy repo structure (OSP-core, docs, wrappers)
This includes a section where we explain which code is located in which directory? (I think it should)

What do you think @aaronAB1993 ?

**Comment by urbanmatthias** [comment]
Maybe releases is not that important, because that is done by us in any case?

**Comment by urbanmatthias** [comment]
Maybe explain the importance of API documentation and unittests, the docstring style and which checks the CI performs.

**Comment by pablo-de-andres** [comment]
Potential sections:

- General organisation
- General workflow (issues and PR with review)
- Coding
   - Documenting style
   - Testing
