### ISSUE TITLE
osp-core is open source

### ISSUE THREAD

**Issue by urbanmatthias** [simphony/docs#48]
![image](https://user-images.githubusercontent.com/42069939/100713247-4cc46000-33b4-11eb-9871-6f6b22a9e849.png)

**Comment by urbanmatthias** [comment]
To counter the confusion: In the text there is written that osp-core will become and open source project. It already is, though.

**Comment by pablo-de-andres** [comment]
The confusing description is not in the issue, but in the docs ;)
