### ISSUE TITLE
Maybe add conda as installation option instead of venv

### ISSUE THREAD

**Issue by urbanmatthias** [simphony/docs#50]
![image](https://user-images.githubusercontent.com/42069939/100714291-dc1e4300-33b5-11eb-8bbb-bdd3d2f22a7d.png)

**Comment by pablo-de-andres** [comment]
Why not both?
What are the commands you use to activate conda?

**Comment by urbanmatthias** [comment]
both is good

```sh
conda create -n <env name>
conda activate <env name>
```
