### ISSUE TITLE
No documentation for keyword 'format'

### ISSUE THREAD

**Issue by yoavnash** [simphony/docs#67]
In the yml configuration file for installing OWL ontologies, the keyword `format` is not specified, which is relevant if the file that is being installed has a specific format. For example:
```yml
...
format: turtle
```
Link to the docs page: https://simphony.readthedocs.io/en/latest/owl.html

**Comment by yoavnash** [comment]
Related to https://github.com/simphony/osp-core/issues/557

**Comment by pablo-de-andres** [comment]
Is the keyword still supported, then?
@urbanmatthias

**Comment by urbanmatthias** [comment]
it is
