### ISSUE TITLE
update changes related to the ontology

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/docs#7]
Define a proper section about the ontology.

In the ontology formats, split between YAML and OWL. 
- YAML:
  - Does not require ALL_UPPER anymore.
  - Example for the attribute format in YAML.
  - None as a possible default value for a data attribute.
  - Explanation about the relationship characteristics
- OWL:
  -  Add information about the format

**Comment by pablo-de-andres** [comment]
@urba this has been taken care of, right?

**Comment by urbanmatthias** [comment]
Si
