### ISSUE TITLE
Add awesome figure to contribute

### ISSUE THREAD

**Issue by urbanmatthias** [simphony/docs#70]
![flowchart](https://user-images.githubusercontent.com/42069939/107525506-322e1480-6bb7-11eb-9929-ed4f61c5cb7d.png)

**Comment by pablo-de-andres** [comment]
The long arrow in master is not centered :confused:

**Comment by urbanmatthias** [comment]
trueee

**Comment by urbanmatthias** [comment]
![SimPhoNy-dev-workflow](https://user-images.githubusercontent.com/42069939/108035760-9cbbd600-7037-11eb-9cfc-2fa7723e9424.png)

**Comment by pablo-de-andres** [comment]
The rendering of the docs on ReadTheDocs is missing line breaks

**Comment by kysrpex** [comment]
I rendered this locally and looks good now!
