### ISSUE TITLE
Add video to coupling and linking section of the Motivation

### ISSUE THREAD

**Issue by pablo-de-andres** [simphony/docs#76]
https://user-images.githubusercontent.com/9430234/112157999-09eafa00-8be8-11eb-9ccd-bc874a0f5580.mp4

https://user-images.githubusercontent.com/9430234/112158002-0a839080-8be8-11eb-9464-b74db5c20984.mp4

**Comment by kysrpex** [comment]
@pablo-de-andres What's the source of these videos btw? Do we have permission to use them?

**Comment by pablo-de-andres** [comment]
As far as I know, they come from SimPhoNy v1.
I took them from some of our presentations/workshops
