### ISSUE TITLE
Redesign the landing page

### ISSUE THREAD

**Issue by kysrpex** [simphony/docs#78]
We are taking too little advantage of the [landing page](https://simphony.readthedocs.io/en/latest/index.html) of the docs, it is not helping the user at all. 

I checked a few projects, and some of the best examples that I saw on how to make a good landing page are [pandas ](https://pandas.pydata.org/docs/index.html) or [AiiDa](https://aiida.readthedocs.io/projects/aiida-core/en/latest/index.html#). They just help you decide very quickly where do you want to go. [rdflib ](https://rdflib.readthedocs.io/en/stable/) also does it similarly, it is just not as eye-catching.

We would not lose anything relevant, as the index is already on the left-hand side of the website, and the compatibility matrix is not really necessary (see issue #79).

**Comment by pablo-de-andres** [comment]
I believe some of those examples are achieved with the [sphinx panels](https://sphinx-panels.readthedocs.io/en/latest/) extensions.
Probably worth looking into it.

**Comment by harrytodorov** [comment]
And to append a bit to @kysrpex's comment: it will be nice to have a short 1-2 sentences of description of SimPhoNy
