### ISSUE TITLE
Reference terminology terms

### ISSUE THREAD

**Issue by harrytodorov** [simphony/docs#83]
Rather than just listing a [list of terminology](https://simphony.readthedocs.io/en/latest/about.html#terminology) in the Introduction section, we should make it easier for the reader to look these up.

Here are two ideas, which come up to my mind
1. Add a reference link to the term in the following sections
2. (Better option IMO) Hover-over (I guess the proper term for it is tooltip) text at each occurrence of the term (an example can be found on [this page](https://wjakob.github.io/nori/)). 

![Screenshot 2021-03-25 153222](https://user-images.githubusercontent.com/6623554/112490064-56b50900-8d7f-11eb-9fc1-7e474f2a0b2e.jpg)

**Comment by pablo-de-andres** [comment]
[Sphinx-hoverxref](https://github.com/readthedocs/sphinx-hoverxref) might be useful for that

**Comment by kysrpex** [comment]
The hover-over is just great. I would do both (hover+link) so that mobile users still can access the meaning of the term.

**Comment by pablo-de-andres** [comment]
Then we can move the terminology towards the end of the docs, since the user will mainly get there by the links

**Comment by harrytodorov** [comment]
After a discussion (see for more details #117), we have decided to halt the integration of tooltips into the docs, as maintaining and extending these long term would require too much manual labour.

If the developers of `sphinx-hoverxref` decide to add support for the Markdown format, we can reconsider continuing the work on this issue. We have opened an issue (regarding the support of Markdown) at `sphinx-hoverxref`'s GitHub repository (see [here](https://github.com/readthedocs/sphinx-hoverxref/issues/114))

**Comment by kysrpex** [comment]
> After a discussion (see for more details #117), we have decided to halt the integration of tooltips into the docs, as maintaining and extending these long term would require too much manual labour.
> 
> If the developers of `sphinx-hoverxref` decide to add support for the Markdown format, we can reconsider continuing the work on this issue. We have opened an issue (regarding the support of Markdown) at `sphinx-hoverxref`'s GitHub repository (see [here](https://github.com/readthedocs/sphinx-hoverxref/issues/114))

Then I am closing this issue. We can reopen it if Markdown support is added to `sphinx-hoverxref`. Anyway, thank you for the research and the work!
